[project]
name = "fishscriptinstall"
version = "0.1.0"
description = "A collection of awesome fish scripts"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.2.1",
]
